version: "3.7"

networks:
  docker-internal:
    external: true

services:
  con-wiki:
    image: requarks/wiki:2
    restart: unless-stopped
    depends_on:
      - con-wiki-db
    environment:
      DB_TYPE: postgres
      DB_HOST: con-wiki-db
      DB_PORT: 5432
      DB_USER: wikijs
      #DB_PASS: SECRET
      DB_NAME: wiki
      LOG_LEVEL: silly
    networks:
      docker-internal:
      default:
    labels:
      # enable
      traefik.enable: "true"
      #
      # specify network to detect ip of container
      traefik.docker.network: "docker-internal"
      #
      # backend settings
      traefik.http.services.wiki-backend.loadbalancer.server.port: 3000
      traefik.http.services.wiki-backend.loadbalancer.server.scheme: http
      #
      # redirect middleware for port 80->443
      traefik.http.middlewares.wiki-https-redirect.redirectscheme.scheme: https
      #
      # http router with middleware
      traefik.http.routers.wiki-http.entrypoints: web
      traefik.http.routers.wiki-http.middlewares: wiki-https-redirect, whitelist-from-internal@file
      traefik.http.routers.wiki-http.rule: Host(`wiki.houseofnerds.it`)
      #
      #
      # https middleware (force STS)
      traefik.http.middlewares.wiki-https.headers.forceSTSHeader: true
      traefik.http.middlewares.wiki-https.headers.stsSeconds: 15552000
      #
      #
      # https router
      traefik.http.routers.wiki-https.entrypoints: websecure
      traefik.http.routers.wiki-https.middlewares: wiki-https, whitelist-from-internal@file
      traefik.http.routers.wiki-https.rule: Host(`wiki.houseofnerds.it`)
      traefik.http.routers.wiki-https.service: wiki-backend
      traefik.http.routers.wiki-https.tls: true
      traefik.http.routers.wiki-https.tls.certResolver: haseacme

  con-wiki-db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: wiki
      #POSTGRES_PASSWORD: SECRET
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - /docker-data/wiki-db:/var/lib/postgresql/data
    networks:
      default:
