name: deploy-test

on:
  push:
    branches:
      - main
    paths:
      # first allow all folders - then decline the technical ones 
      - 'wgpve-docker.houseofnerds.it/testcontainer/**'


jobs:
  deployment:
    uses: houseofnerds-it/workflow-compose-management/.github/workflows/main-task_deployment.yml@main
    with:
      action: "deployment-container"
    secrets: inherit