name: deploy

on:
  push:
    branches:
      - main
    paths:
      # first allow all folders - then decline the technical ones 
      - '**'
      # exclude test container (is used to develop the ci)
      - '!**/testcontainer/**'
      # exclude so changes to the workflows dont trigger a docker deployment
      - '!.github/**'
      # exclude network files - will be handled separatly
      - '!**/network/**'


jobs:
  deployment:
    uses: houseofnerds-it/workflow-compose-management/.github/workflows/deployment.yml@v0.1
    with:
      action: "deployment-container"
    secrets: inherit